# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := base
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-fno-exceptions \
	-fno-strict-aliasing \
	-fstack-protector-all \
	-fvisibility=hidden \
	-g \
	-pipe \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-mfpmath=sse \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-std=gnu++11 \
	-Wsign-compare \
	-std=c++0x

INCS_Debug := \
	-I.

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-fno-exceptions \
	-fno-strict-aliasing \
	-fstack-protector-all \
	-fvisibility=hidden \
	-g \
	-pipe \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-mfpmath=sse \
	-O3 \
	-fdata-sections \
	-ffunction-sections \
	-fno-ident

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-std=gnu++11 \
	-Wsign-compare \
	-std=c++0x

INCS_Release := \
	-I.

OBJS := \
	$(obj).target/$(TARGET)/base/at_exit.o \
	$(obj).target/$(TARGET)/base/atomicops_internals_x86_gcc.o \
	$(obj).target/$(TARGET)/base/base_paths.o \
	$(obj).target/$(TARGET)/base/base_paths_posix.o \
	$(obj).target/$(TARGET)/base/base_switches.o \
	$(obj).target/$(TARGET)/base/bind_helpers.o \
	$(obj).target/$(TARGET)/base/callback_helpers.o \
	$(obj).target/$(TARGET)/base/callback_internal.o \
	$(obj).target/$(TARGET)/base/command_line.o \
	$(obj).target/$(TARGET)/base/cpu.o \
	$(obj).target/$(TARGET)/base/debug/alias.o \
	$(obj).target/$(TARGET)/base/debug/asan_invalid_access.o \
	$(obj).target/$(TARGET)/base/debug/crash_logging.o \
	$(obj).target/$(TARGET)/base/debug/debugger.o \
	$(obj).target/$(TARGET)/base/debug/debugger_posix.o \
	$(obj).target/$(TARGET)/base/debug/dump_without_crashing.o \
	$(obj).target/$(TARGET)/base/debug/proc_maps_linux.o \
	$(obj).target/$(TARGET)/base/debug/profiler.o \
	$(obj).target/$(TARGET)/base/debug/stack_trace.o \
	$(obj).target/$(TARGET)/base/debug/stack_trace_posix.o \
	$(obj).target/$(TARGET)/base/debug/task_annotator.o \
	$(obj).target/$(TARGET)/base/debug/trace_event_argument.o \
	$(obj).target/$(TARGET)/base/debug/trace_event_impl.o \
	$(obj).target/$(TARGET)/base/debug/trace_event_impl_constants.o \
	$(obj).target/$(TARGET)/base/debug/trace_event_memory.o \
	$(obj).target/$(TARGET)/base/debug/trace_event_synthetic_delay.o \
	$(obj).target/$(TARGET)/base/debug/trace_event_system_stats_monitor.o \
	$(obj).target/$(TARGET)/base/environment.o \
	$(obj).target/$(TARGET)/base/files/file.o \
	$(obj).target/$(TARGET)/base/files/file_enumerator.o \
	$(obj).target/$(TARGET)/base/files/file_enumerator_posix.o \
	$(obj).target/$(TARGET)/base/files/file_path.o \
	$(obj).target/$(TARGET)/base/files/file_path_constants.o \
	$(obj).target/$(TARGET)/base/files/file_posix.o \
	$(obj).target/$(TARGET)/base/files/file_util.o \
	$(obj).target/$(TARGET)/base/files/file_util_linux.o \
	$(obj).target/$(TARGET)/base/files/file_util_posix.o \
	$(obj).target/$(TARGET)/base/files/scoped_file.o \
	$(obj).target/$(TARGET)/base/files/scoped_temp_dir.o \
	$(obj).target/$(TARGET)/base/hash.o \
	$(obj).target/$(TARGET)/base/json/json_file_value_serializer.o \
	$(obj).target/$(TARGET)/base/json/json_parser.o \
	$(obj).target/$(TARGET)/base/json/json_reader.o \
	$(obj).target/$(TARGET)/base/json/json_string_value_serializer.o \
	$(obj).target/$(TARGET)/base/json/json_value_converter.o \
	$(obj).target/$(TARGET)/base/json/json_writer.o \
	$(obj).target/$(TARGET)/base/json/string_escape.o \
	$(obj).target/$(TARGET)/base/lazy_instance.o \
	$(obj).target/$(TARGET)/base/location.o \
	$(obj).target/$(TARGET)/base/logging.o \
	$(obj).target/$(TARGET)/base/md5.o \
	$(obj).target/$(TARGET)/base/memory/ref_counted.o \
	$(obj).target/$(TARGET)/base/memory/ref_counted_memory.o \
	$(obj).target/$(TARGET)/base/memory/singleton.o \
	$(obj).target/$(TARGET)/base/memory/weak_ptr.o \
	$(obj).target/$(TARGET)/base/message_loop/incoming_task_queue.o \
	$(obj).target/$(TARGET)/base/message_loop/message_loop.o \
	$(obj).target/$(TARGET)/base/message_loop/message_loop_proxy.o \
	$(obj).target/$(TARGET)/base/message_loop/message_loop_proxy_impl.o \
	$(obj).target/$(TARGET)/base/message_loop/message_pump.o \
	$(obj).target/$(TARGET)/base/message_loop/message_pump_default.o \
	$(obj).target/$(TARGET)/base/message_loop/message_pump_libevent.o \
	$(obj).target/$(TARGET)/base/path_service.o \
	$(obj).target/$(TARGET)/base/pending_task.o \
	$(obj).target/$(TARGET)/base/pickle.o \
	$(obj).target/$(TARGET)/base/process/internal_linux.o \
	$(obj).target/$(TARGET)/base/process/kill.o \
	$(obj).target/$(TARGET)/base/process/kill_posix.o \
	$(obj).target/$(TARGET)/base/process/launch.o \
	$(obj).target/$(TARGET)/base/process/launch_posix.o \
	$(obj).target/$(TARGET)/base/process/memory.o \
	$(obj).target/$(TARGET)/base/process/memory_linux.o \
	$(obj).target/$(TARGET)/base/process/process_handle_linux.o \
	$(obj).target/$(TARGET)/base/process/process_handle_posix.o \
	$(obj).target/$(TARGET)/base/process/process_iterator.o \
	$(obj).target/$(TARGET)/base/process/process_iterator_linux.o \
	$(obj).target/$(TARGET)/base/process/process_linux.o \
	$(obj).target/$(TARGET)/base/process/process_metrics.o \
	$(obj).target/$(TARGET)/base/process/process_metrics_linux.o \
	$(obj).target/$(TARGET)/base/process/process_metrics_posix.o \
	$(obj).target/$(TARGET)/base/profiler/alternate_timer.o \
	$(obj).target/$(TARGET)/base/profiler/scoped_profile.o \
	$(obj).target/$(TARGET)/base/profiler/scoped_tracker.o \
	$(obj).target/$(TARGET)/base/profiler/tracked_time.o \
	$(obj).target/$(TARGET)/base/rand_util.o \
	$(obj).target/$(TARGET)/base/rand_util_posix.o \
	$(obj).target/$(TARGET)/base/run_loop.o \
	$(obj).target/$(TARGET)/base/safe_strerror_posix.o \
	$(obj).target/$(TARGET)/base/sequence_checker_impl.o \
	$(obj).target/$(TARGET)/base/sequenced_task_runner.o \
	$(obj).target/$(TARGET)/base/strings/string16.o \
	$(obj).target/$(TARGET)/base/strings/string_number_conversions.o \
	$(obj).target/$(TARGET)/base/strings/string_piece.o \
	$(obj).target/$(TARGET)/base/strings/string_split.o \
	$(obj).target/$(TARGET)/base/strings/string_util.o \
	$(obj).target/$(TARGET)/base/strings/string_util_constants.o \
	$(obj).target/$(TARGET)/base/strings/stringprintf.o \
	$(obj).target/$(TARGET)/base/strings/sys_string_conversions_posix.o \
	$(obj).target/$(TARGET)/base/strings/utf_string_conversion_utils.o \
	$(obj).target/$(TARGET)/base/strings/utf_string_conversions.o \
	$(obj).target/$(TARGET)/base/synchronization/cancellation_flag.o \
	$(obj).target/$(TARGET)/base/synchronization/condition_variable_posix.o \
	$(obj).target/$(TARGET)/base/synchronization/lock.o \
	$(obj).target/$(TARGET)/base/synchronization/lock_impl_posix.o \
	$(obj).target/$(TARGET)/base/synchronization/waitable_event_posix.o \
	$(obj).target/$(TARGET)/base/sys_info.o \
	$(obj).target/$(TARGET)/base/sys_info_linux.o \
	$(obj).target/$(TARGET)/base/sys_info_posix.o \
	$(obj).target/$(TARGET)/base/task_runner.o \
	$(obj).target/$(TARGET)/base/third_party/dmg_fp/dtoa_wrapper.o \
	$(obj).target/$(TARGET)/base/third_party/dmg_fp/g_fmt.o \
	$(obj).target/$(TARGET)/base/third_party/dynamic_annotations/dynamic_annotations.o \
	$(obj).target/$(TARGET)/base/third_party/icu/icu_utf.o \
	$(obj).target/$(TARGET)/base/third_party/nspr/prtime.o \
	$(obj).target/$(TARGET)/base/third_party/xdg_user_dirs/xdg_user_dir_lookup.o \
	$(obj).target/$(TARGET)/base/thread_task_runner_handle.o \
	$(obj).target/$(TARGET)/base/threading/non_thread_safe_impl.o \
	$(obj).target/$(TARGET)/base/threading/platform_thread_linux.o \
	$(obj).target/$(TARGET)/base/threading/platform_thread_posix.o \
	$(obj).target/$(TARGET)/base/threading/post_task_and_reply_impl.o \
	$(obj).target/$(TARGET)/base/threading/sequenced_worker_pool.o \
	$(obj).target/$(TARGET)/base/threading/simple_thread.o \
	$(obj).target/$(TARGET)/base/threading/thread.o \
	$(obj).target/$(TARGET)/base/threading/thread_checker_impl.o \
	$(obj).target/$(TARGET)/base/threading/thread_collision_warner.o \
	$(obj).target/$(TARGET)/base/threading/thread_id_name_manager.o \
	$(obj).target/$(TARGET)/base/threading/thread_local_posix.o \
	$(obj).target/$(TARGET)/base/threading/thread_local_storage.o \
	$(obj).target/$(TARGET)/base/threading/thread_local_storage_posix.o \
	$(obj).target/$(TARGET)/base/threading/thread_restrictions.o \
	$(obj).target/$(TARGET)/base/threading/worker_pool.o \
	$(obj).target/$(TARGET)/base/threading/worker_pool_posix.o \
	$(obj).target/$(TARGET)/base/time/time.o \
	$(obj).target/$(TARGET)/base/time/time_posix.o \
	$(obj).target/$(TARGET)/base/timer/timer.o \
	$(obj).target/$(TARGET)/base/tracked_objects.o \
	$(obj).target/$(TARGET)/base/tracking_info.o \
	$(obj).target/$(TARGET)/base/values.o \
	$(obj).target/$(TARGET)/base/vlog.o \
	$(obj).target/$(TARGET)/third_party/superfasthash/superfasthash.o \
	$(obj).target/$(TARGET)/base/nix/xdg_util.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wl,--as-needed \
	-Wl,-z,noexecstack

LDFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wl,--as-needed \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--gc-sections

LIBS :=

$(obj).target/libbase.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libbase.a: LIBS := $(LIBS)
$(obj).target/libbase.a: TOOLSET := $(TOOLSET)
$(obj).target/libbase.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/libbase.a
# Add target alias
.PHONY: base
base: $(obj).target/libbase.a

# Add target alias to "all" target.
.PHONY: all
all: base

