# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := test_base
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-fno-exceptions \
	-fno-strict-aliasing \
	-fstack-protector-all \
	-fvisibility=hidden \
	-g \
	-pipe \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-mfpmath=sse \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-std=gnu++11 \
	-Wsign-compare \
	-std=c++0x

INCS_Debug := \
	-I.

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-fno-exceptions \
	-fno-strict-aliasing \
	-fstack-protector-all \
	-fvisibility=hidden \
	-g \
	-pipe \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-mfpmath=sse \
	-O3 \
	-fdata-sections \
	-ffunction-sections \
	-fno-ident

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-std=gnu++11 \
	-Wsign-compare \
	-std=c++0x

INCS_Release := \
	-I.

OBJS := \
	$(obj).target/$(TARGET)/main.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/libbase.a $(obj).target/third_party/libevent/libevent.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wl,--as-needed \
	-Wl,-z,noexecstack \
	-pthread

LDFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wl,--as-needed \
	-Wl,-z,noexecstack \
	-pthread \
	-Wl,-O1 \
	-Wl,--gc-sections

LIBS := \
	-lrt

$(builddir)/test_base: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/test_base: LIBS := $(LIBS)
$(builddir)/test_base: LD_INPUTS := $(OBJS) $(obj).target/libbase.a $(obj).target/third_party/libevent/libevent.a
$(builddir)/test_base: TOOLSET := $(TOOLSET)
$(builddir)/test_base: $(OBJS) $(obj).target/libbase.a $(obj).target/third_party/libevent/libevent.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/test_base
# Add target alias
.PHONY: test_base
test_base: $(builddir)/test_base

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/test_base

